### ISSUE TITLE
Update RoyalRoadL

### ISSUE THREAD

**Issue by Eltrakne** [TUSF/RRL2epub#1]
Thank you for your work,
I use your program during the holidays without worries but since the updated on royalroad website this week I get the error "Error communicating with SDR, or with The Given Fiction ID".
I will try  work on the problem as soon as possible.
I will also look at whether it's possible to change the name of the document in case of special characters in the title (which currently prevents the creation of the document).
(I use the windows version).
Thx

**Comment by TUSF** [comment]
I hadn't noticed the update to RoyalRoadL until yesterday, but in light of the update, I'll go ahead and reprogram how the program operates when I have the time.

**Comment by TUSF** [comment]
This issue should(?) be fixed now. I'm not sure what characters break on windows, but for now spaces, colons and commas, but I'll be honest that I'm not sure what other characters might be a problem.

**Comment by Eltrakne** [comment]
Tank you,
I'll try it right now and if there is a character that does not want to pass I will let you know.
Characters that can't be use on file name are more or less all ascii code characters 0 to 47 and a few more (but only a few are usable, it is difficult to use the backspace for example). Those that can be used easily and break are
\ /: *? "<> | (that's what windows tell me when I try to use one of them)
There are others but they are not usable in practical ways (like backspace previously).
Thanks again.

**Comment by TUSF** [comment]
I made a change in the source (haven't put it up as a _release_ though), so now it should be closer to replacing illegal characters; specifically control characters, spaces, and the punctuation you mention should all be replaced with an underscore. (Clusters of them should become a single underscore.

I'll close this issue for now, but if you find an issue related to this, let me know.
