### ISSUE TITLE
assignment mismatch 2 variables but 1 values

### ISSUE THREAD

**Issue by slpixe** [TUSF/RRL2epub#3]
Hi, been getting this error when trying to build, it is an issue with the epub3 writer?

**Comment by slpixe** [comment]
Awesome works straight away now for RRL (WN finds the image, but not the chapters)
Thanks for sorting it so quickly

**Comment by slpixe** [comment]
Started looking at having it support WN.

Looks like they changed it so the TOC data is behind an api request (which requires a session token)

Closing this issue as you got this working, cheers.
I'll let you know if I make any progress with the WN stuff

**Comment by TUSF** [comment]
@slpixe Just letting you know that I redid most of the handler for WN, so it works, but it could use some touch ups.

**Comment by slpixe** [comment]
@TUSF thanks, you got a lot further than I did.

I kept switching between different JSON libraries because I thought they required predefining structs
